In [1]:
import numpy

In [2]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [3]:
import math

In [4]:
print(dir(math)) 

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [5]:
print(dir(numpy.array))

['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__text_signature__']


In [6]:
# vector... []

import numpy as np

vec = [234,3,45,4,3,45,4, 34, 54, 3,45,3,45]

arr = np.array(vec); arr

array([234,   3,  45,   4,   3,  45,   4,  34,  54,   3,  45,   3,  45])

In [7]:
arr.dtype

dtype('int32')

In [8]:
vec1 = [234,3,45,4,3,45,4,34,54,3,45,3, 'mango',45] 
arr1= np.array(vec1); arr1

array(['234', '3', '45', '4', '3', '45', '4', '34', '54', '3', '45', '3',
       'mango', '45'], dtype='<U11')

In [12]:
# multinested array....

lst1= [12,34,5,23]
lst2= [13,14,5,23]
lst3 =[12,39,5,24]
lst4 = [10,14,51,23]

arr2 = np.array([lst1, lst2, lst3, lst4]);arr2

array([[12, 34,  5, 23],
       [13, 14,  5, 23],
       [12, 39,  5, 24],
       [10, 14, 51, 23]])

In [13]:
arr2*2

array([[ 24,  68,  10,  46],
       [ 26,  28,  10,  46],
       [ 24,  78,  10,  48],
       [ 20,  28, 102,  46]])

In [14]:
type(arr2)

numpy.ndarray

In [18]:
arr2.shape

(4, 4)

In [19]:
arr2[0]

array([12, 34,  5, 23])

In [16]:
arr2.ndim

2

In [17]:
arr2.reshape(2,2,4)

array([[[12, 34,  5, 23],
        [13, 14,  5, 23]],

       [[12, 39,  5, 24],
        [10, 14, 51, 23]]])

In [22]:
arr2[0][0]

12

In [23]:
arr2*arr2

array([[ 144, 1156,   25,  529],
       [ 169,  196,   25,  529],
       [ 144, 1521,   25,  576],
       [ 100,  196, 2601,  529]])

In [24]:
aa = np.random.randn(4,4)

In [25]:
aa.reshape(8,2)

array([[ 1.04794099,  0.37424903],
       [-0.14518863, -1.36879931],
       [ 1.3212611 ,  0.03691537],
       [ 0.10957893,  1.0146369 ],
       [-0.51889666, -2.15891772],
       [ 2.02799319, -0.60779613],
       [-0.23638247,  0.75777089],
       [ 0.38734607, -0.64472737]])

In [29]:
aaa = np.ones((4,3))

In [27]:
len(arr2[0][0])

TypeError: object of type 'numpy.int32' has no len()

In [30]:
b = aaa.copy()